### ISSUE TITLE
Set color function doesn't seem to do anything

### ISSUE THREAD

**Issue by Velaseriat** [cvuchener/k40-set-color#2]
pulse works,
cycles simply sets it to blue but does nothing afterwards
off reverts it back to what it was originally (red for me)
but manually setting the color doesn't seem to work.
It does tell me 
Status: blah blah
Set color 0000FF
but it doesn't reflect that color.

ubuntu 16.04

**Comment by Velaseriat** [comment]
It exhibits the same behavior as this other github tool:
https://github.com/bennyPerth/Corsair-K40-colours/issues/new

pulse works, when i try to cycle colors it just turns blue, and i cant change colors.
i think its something on my end. im running Ubuntu 16.04.

Any idea what is causing this?

**Comment by cvuchener** [comment]
I don't own a K40, I wrote this while trying to reverse the protocol for someone else. It is a quick and dirty hack to test some USB commands. Not everything is understood.

You can also test this program: https://github.com/cvuchener/corsair-usb-config It only implements features I think I understand (although it never was tested with a K40): for colors that means only setting the color of a given profile. K40 macros was never tested and but in the few USB dumps I read, it looked exactly like the K90.

> Set color function doesn't seem to do anything

I never managed to make this one work, but setting a color for a specific profile (using option -p) should work.

I expected it to change the color temporarily (not saved in a profile). I think there must be some way to switch the keyboard to a driver-controlled mode instead hardware-controlled but I don't know how.

> cycles simply sets it to blue but does nothing afterwards

If I remember correctly, Corsair software on Windows send regular commands to the device for the "cycle" animation. So I don't actually expect it to cycle, I think it is meant to just fade to another color. But I am not sure about how to use it.

Does it became blue instantly or does it fade progressively? Does it revert to red after some time?

> Any idea what is causing this?

My misunderstanding of the protocol. If you are interested, we could try again to make these features work.

Most of the discussion with my previous user was on the corsair forum: http://forum.corsair.com/v3/showthread.php?t=149621

**Comment by Velaseriat** [comment]
I'd be interested, except I'm pretty green in this department. I do plan on combing your code to learn how this stuff works. 

I have this stupid rainbow bash prompt going (also inexperienced with that) and I want to uselessly set the color of the keyboard to reflect the color of the prompt. That's the end goal.

If I make any headway with my K40 I'll do a proper fork and come back to this. Thanks again for the very very detailed response =)

**Comment by Velaseriat** [comment]
This tool works as you have described above. I think setting it to hardware mode, profile 1, max brightness, and animation off executed the desired behavior. 

Thank you very much!

Running on Ubuntu 16.04 with a k40 keyboard.

**Comment by debianmain1** [comment]
I'm still interested in working with this--have been involved with other things for the last few months & just getting back to playing with settings on the keyboard. contact me if you need/want help.
